sap.ui.define([
    "sap/ui/model/json/JSONModel",
    "sap/ui/Device"
],
    function (JSONModel, Device) {
        "use strict";

        return {
            /**
             * Provides runtime info for the device the UI5 app is running on as JSONModel
             */
            createDeviceModel: function () {
                var oModel = new JSONModel(Device);
                oModel.setDefaultBindingMode("OneWay");
                return oModel;
            },
            ContextModel1: function () {
                var mockdata = {
                    ContextModel: function () {
                        var mockdata = {
                            "PURCHASING_GROUP": "",
                            "PO_UNIT_OF_MEASURE": "",
                            "PURCHASING_VALUE_KEY": "",
                            "GOOD_RECIEPT_PROCESSING_TIME": "",
                            "AUTOMATIC_PO_ALLOWED": false,
                            "ALTERNATIVE_UOM_TO_STOCKKEEPING": "",
                            "DENOMINATOR_CONVERSION_TO_BUOM": 0,
                            "NUMERATOR_CONVERSION_TO_BUOM": 0,
                            "INTERNATIONAL_ARTICLE_NUMBER": 0,
                            "CATEGORY_OF_INTERNATION_ARTICLE_NO": "",
                            "LENGTH_UOM": "",
                            "WIDTH_UOM": "",
                            "HEIGHT_UOM": "",
                            "UNIT_OF_DIMENSION_LWM": "",
                            "VOLUME_UOM": "",
                            "VOLUME_UNIT_UOM": "",
                            "GROSS_WEIGHT_UOM": "",
                            "WEIGHT_UNIT_UOM": "",
                            "STORAGE_LOCATION": "",
                            "STORAGE_BIN": "",
                            "MAXIMUM_STORAGE_PERIOD": 0,
                            "TIME_UNIT": "",
                            "BATCH_MGMT_REQUIRE_INDICATOR": "",
                            "MATERIALTYPE": "",
                            "MaterialTypeName": "",
                            "PlantName": "",
                            "CompanyCodeName": "",
                            "MaterialGroupText": "",
                            "UnitOfMeasureLongName": "",
                            "DivisionName": "",
                            "UnitOfMeasure": "",
                            "PLANT": "",
                            "Company": "",
                            "MATERIALGROUPTEXT": "",
                            "UNITOFMEASURE": "",
                            "Division": "",
                            "Category": "",
                            "MaterialDescription": "",
                            "MaterialLongDescription": "",
                            "ID": "",
                            "Timestamp": "",
                            "Status": "",
                            "CONTROL_CODE": "",
                            "PROFIT_CENTER": "",
                            "VALUATION_TYPE": "",
                            "VALUATION_CATEGORY": "",
                            "VALUATION_CLASS": "",
                            "PRICE_CONTROL_INDICATOR": false,
                            "MOVING_AVG_PRICE_PER_PERIODIC_UNIT_PRICE": "",
                            "PRICE_UNIT": "",
                            "FUTURE_PRICE": 0,
                            "ORIGIN_OF_MATERIAL": "",
                            "MATERIAL_COST_WITH_QUANTITY_STRUCTURE": "",
                            "MATERIAL_RELATED_ORIGIN": "",
                            "FUTURE_PLANNED_PRICE_1": 0,
                            "DATE_FROM_FUTURE_PLAN1_VALID": "",
                            "FUTURE_PLANNED_PRICE_2": 0,
                            "DATE_FROM_FUTURE_PLAN2_VALID": "",
                            "DEPARTURE_COUNTRY_GOODS_SENT": "",
                            "TAX_CATEGORY_1": "",
                            "TAX_CLASSIFICATION_MATERIAL1": "",
                            "TAX_CATEGORY_2": "",
                            "TAX_CLASSIFICATION_MATERIAL2": "",
                            "TAX_CATEGORY_3": "",
                            "TAX_CLASSIFICATION_MATERIAL3": "",
                            "SALES_ORGANIZATION": "",
                            "DISTRIBUTION_CHANNEL": "",
                            "SALES_UNIT": "",
                            "DELIVERING_PLANT": "",
                            "CASH_DISCOUNT_INDICATOR": false,
                            "MIN_ORDER_QUANTITY_BUOM": 0,
                            "MIN_DELIVERY_QUANTITY": "",
                            "DELIVERY_UNIT": "",
                            "UOM_DELIVERY_UNIT": "",
                            "ROUNDING_PROFILE": "",
                            "MATERIAL_STATISTIC_GROUP": "",
                            "ITEM_CATEGORY_GROUP": "",
                            "PRICING_REFERENCE_MATERIAL": "",
                            "MATERIAL_PRICE_GROUP": "",
                            "ACCOUNT_ASSIGNMENT_GROUP": "",
                            "COMISSION_GROUP": "",
                            "MATERIAL_GROUP_1": "",
                            "MATERIAL_GROUP_2": "",
                            "MATERIAL_GROUP_3": "",
                            "MATERIAL_GROUP_4": "",
                            "MATERIAL_GROUP_5": "",
                            "TRANSPORTATION_GROUP": "",
                            "LOADING_GROUP": "",
                            "DeliveringPlant": "",
                            "PurchasingGroup": "",
                            "purchasingunitmeasure": "",
                            "PurchasengValueKey": "",
                            "GoodReceiptProcessingTime": "",
                            "LengthData": "",
                            "CATLOG_PROFILE": "",
                            "QM_IN_PROC_ACTIVE": false,
                            "HANDLING_UNIT_TYPE": "",
                            "INSPECTION_TYPE_MATERIAL_COMBINATION_IS_ACTIVE": "",
                            "MINIMUM_REMAINING_SHELF_LIFE": "",
                            "TOTAL_SHELF_LIFE": "",
                            "PERIOD_INDICATOR_SLED": "",
                            "LEVEL_1": "",
                            "LEVEL_2": "",
                            "LEVEL_3": "",
                            "LEVEL_4": "",
                            "LEVEL_5": "",
                            "MAX_LEVEL": 0,
                            "LEVEL_NAME": "",
                            "LEVEL_COUNT": 0,
                            "MRP_GROUP": "",
                            "ABC_INDICATOR": "",
                            "MRP_TYPE": "",
                            "MRP_CONTROLLER": "",
                            "REORDER_POINT": "",
                            "LOT_SIZING_PROC": "",
                            "MINIMUM_LOT_SIZE": "",
                            "MAXIMUM_LOT_SIZE": "",
                            "FIXED_LOT_SIZE": "",
                            "MAX_STOCK_LEVEL": "",
                            "ASSEMBLY_SCRAP_PERCENTAGE": 0,
                            "ROUNDING_PROFILE": "",
                            "PROCUREMENT_TYPE": "",
                            "SPECIAL_PROCUREMENT_TYPE": "",
                            "INDICATOR_BACKFLUSH": "",
                            "STORAGE_LOCATION_FOR_EXTERNAL_PROC": "",
                            "EditableFinance": true,
                            "Editableproduction": true,
                            "EditableSales": true,
                            "Editableprocurment": true,
                            "EditableMainlevel1": true,
                            "EditableMainlevel2": true,
                            "EditableMainlevel3": true,
                            "EditableMainlevel4": true,
                            "EditableMainlevel5": true,
                            "EditableTemplevel1": false,
                            "EditableTemplevel2": false,
                            "EditableTemplevel3": false,
                            "EditableTemplevel4": false,
                            "EditableTemplevel5": false,
                            "VisibleMainlevel1": true,
                            "VisibleMainlevel2": true,
                            "VisibleMainlevel3": true,
                            "VisibleMainlevel4": true,
                            "VisibleMainlevel5": true,
                            "VisibleTemplevel1": false,
                            "VisibleTemplevel2": false,
                            "VisibleTemplevel3": false,
                            "VisibleTemplevel4": false,
                            "VisibleTemplevel5": false


                        }
                        var myModel = new JSONModel(mockdata);
                        myModel.setDefaultBindingMode("TwoWay");
                        return myModel;
                    }

                }
                var myModel = new JSONModel(mockdata);
                myModel.setDefaultBindingMode("TwoWay");
                return myModel;
            }
        };
    });